# ─────────────────────────────────────────────────────────────────────────────
# Seed : Produits & Matériaux Comparateur
# 30 produits réels marché belge (prix moyens Q1 2026)
# ─────────────────────────────────────────────────────────────────────────────

puts "  → Produits & Matériaux..."

Product.delete_all

# ═══════════════════════════════════════════════════════════════════════════════
# ISOLANTS — TOITURE (7)
# ═══════════════════════════════════════════════════════════════════════════════

Product.create!([
  {
    category: 'insulation',
    subcategory: 'toiture',
    name: 'Laine de roche Rockwool Rockmur',
    brand: 'Rockwool',
    description: 'Isolant minéral haute densité, excellent rapport isolation/feu/acoustique.',
    technical_specs: {
      'lambda' => 0.034,
      'r_value_per_cm' => 0.294,
      'fire_class' => 'A1',
      'water_resistance' => 'excellent',
      'thickness_options_cm' => [10, 12, 14, 16, 20]
    },
    certifications: ['CE', 'EUCEB', 'ACERMI'],
    price_per_unit: 45.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 4.70,  # R-value pour 16cm
    lifespan_years: 50,
    grey_energy_kwh: 150,
    recyclable: true,
    biosourced: false,
    fire_class: 'A1',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.3,
    display_order: 1,
    active: true
  },
  {
    category: 'insulation',
    subcategory: 'toiture',
    name: 'Laine de verre Isover Isoconfort',
    brand: 'Isover',
    description: 'Isolant minéral économique, bon pour toitures inclinées.',
    technical_specs: {
      'lambda' => 0.040,
      'r_value_per_cm' => 0.250,
      'fire_class' => 'A1',
      'water_resistance' => 'moyenne',
      'thickness_options_cm' => [10, 12, 14, 16, 20]
    },
    certifications: ['CE', 'ACERMI'],
    price_per_unit: 38.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 4.00,  # R-value pour 16cm
    lifespan_years: 50,
    grey_energy_kwh: 200,
    recyclable: true,
    biosourced: false,
    fire_class: 'A1',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.0,
    display_order: 2,
    active: true
  },
  {
    category: 'insulation',
    subcategory: 'toiture',
    name: 'PUR / PIR Recticel Eurowall',
    brand: 'Recticel',
    description: 'Mousse rigide haute performance, idéale pour épaisseur réduite.',
    technical_specs: {
      'lambda' => 0.022,
      'r_value_per_cm' => 0.455,
      'fire_class' => 'E',
      'water_resistance' => 'excellent',
      'thickness_options_cm' => [8, 10, 12, 14, 16]
    },
    certifications: ['CE', 'ATG'],
    price_per_unit: 68.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 7.27,  # R-value pour 16cm
    lifespan_years: 50,
    grey_energy_kwh: 1000,
    recyclable: false,
    biosourced: false,
    fire_class: 'E',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.5,
    display_order: 3,
    active: true
  },
  {
    category: 'insulation',
    subcategory: 'toiture',
    name: 'Ouate de cellulose Isocell',
    brand: 'Isocell',
    description: 'Isolant biosourcé par soufflage, excellente régulation hygrométrique.',
    technical_specs: {
      'lambda' => 0.038,
      'r_value_per_cm' => 0.263,
      'fire_class' => 'B',
      'water_resistance' => 'bonne',
      'application' => 'soufflage'
    },
    certifications: ['CE', 'ATG'],
    price_per_unit: 42.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 4.21,  # R-value pour 16cm
    lifespan_years: 50,
    grey_energy_kwh: 60,
    recyclable: true,
    biosourced: true,
    fire_class: 'B',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.4,
    display_order: 4,
    active: true
  },
  {
    category: 'insulation',
    subcategory: 'toiture',
    name: 'Chanvre Biofib Trio',
    brand: 'Biofib',
    description: 'Isolant chanvre 100% naturel, très faible énergie grise.',
    technical_specs: {
      'lambda' => 0.039,
      'r_value_per_cm' => 0.256,
      'fire_class' => 'D',
      'water_resistance' => 'bonne',
      'thickness_options_cm' => [10, 12, 14, 16, 20]
    },
    certifications: ['CE', 'Natureplus'],
    price_per_unit: 52.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 4.10,
    lifespan_years: 50,
    grey_energy_kwh: 45,
    recyclable: true,
    biosourced: true,
    fire_class: 'D',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.2,
    display_order: 5,
    active: true
  },
  {
    category: 'insulation',
    subcategory: 'toiture',
    name: 'Liège expansé Amorim',
    brand: 'Amorim',
    description: 'Isolant naturel 100% biosourcé, très durable, bon déphasage thermique.',
    technical_specs: {
      'lambda' => 0.040,
      'r_value_per_cm' => 0.250,
      'fire_class' => 'E',
      'water_resistance' => 'excellente',
      'thickness_options_cm' => [8, 10, 12, 14, 16]
    },
    certifications: ['CE'],
    price_per_unit: 58.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 4.00,
    lifespan_years: 70,
    grey_energy_kwh: 40,
    recyclable: true,
    biosourced: true,
    fire_class: 'E',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.1,
    display_order: 6,
    active: true
  },
  {
    category: 'insulation',
    subcategory: 'toiture',
    name: 'Panneau PIR Kingspan Thermaroof',
    brand: 'Kingspan',
    description: 'PIR premium ultra-mince, performance maximale pour toitures plates.',
    technical_specs: {
      'lambda' => 0.021,
      'r_value_per_cm' => 0.476,
      'fire_class' => 'E',
      'water_resistance' => 'excellent',
      'usage' => 'toiture_plate'
    },
    certifications: ['CE', 'BBA', 'ATG'],
    price_per_unit: 78.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 7.62,  # R-value 16cm
    lifespan_years: 50,
    grey_energy_kwh: 950,
    recyclable: false,
    biosourced: false,
    fire_class: 'E',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.6,
    display_order: 7,
    active: true
  }
])

# ═══════════════════════════════════════════════════════════════════════════════
# ISOLANTS — MURS (4)
# ═══════════════════════════════════════════════════════════════════════════════

Product.create!([
  {
    category: 'insulation',
    subcategory: 'murs',
    name: 'Laine de roche façade Rockwool FKD',
    brand: 'Rockwool',
    description: "Panneau semi-rigide pour isolation façade par l'extérieur (ITE).",
    technical_specs: {
      'lambda' => 0.036,
      'r_value_per_cm' => 0.278,
      'fire_class' => 'A1',
      'system' => 'ITE'
    },
    certifications: ['CE', 'EUCEB'],
    price_per_unit: 55.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 4.44,  # 16cm
    lifespan_years: 50,
    grey_energy_kwh: 160,
    recyclable: true,
    biosourced: false,
    fire_class: 'A1',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.2,
    display_order: 10,
    active: true
  },
  {
    category: 'insulation',
    subcategory: 'murs',
    name: 'PIR Façade Recticel Powerwall',
    brand: 'Recticel',
    description: 'PIR compressible pour ITE, excellente performance sur épaisseur réduite.',
    technical_specs: {
      'lambda' => 0.023,
      'r_value_per_cm' => 0.435,
      'fire_class' => 'E',
      'system' => 'ITE'
    },
    certifications: ['CE', 'ETA'],
    price_per_unit: 72.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 6.96,  # 16cm
    lifespan_years: 50,
    grey_energy_kwh: 1100,
    recyclable: false,
    biosourced: false,
    fire_class: 'E',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.3,
    display_order: 11,
    active: true
  },
  {
    category: 'insulation',
    subcategory: 'murs',
    name: 'Panneaux en laine de bois Steico Internal',
    brand: 'Steico',
    description: 'Isolant biosourcé intérieur, régulation hygrométrique naturelle.',
    technical_specs: {
      'lambda' => 0.038,
      'r_value_per_cm' => 0.263,
      'fire_class' => 'D',
      'system' => 'ITI'
    },
    certifications: ['CE', 'Natureplus'],
    price_per_unit: 48.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 4.21,  # 16cm
    lifespan_years: 50,
    grey_energy_kwh: 50,
    recyclable: true,
    biosourced: true,
    fire_class: 'D',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.3,
    display_order: 12,
    active: true
  },
  {
    category: 'insulation',
    subcategory: 'murs',
    name: 'Injection polyuréthane coulisse Lapolla',
    brand: 'Lapolla',
    description: 'Mousse PU injectée en coulisse (murs creux), sans travaux lourds.',
    technical_specs: {
      'lambda' => 0.035,
      'r_value_per_cm' => 0.286,
      'application' => 'injection',
      'fire_class' => 'E'
    },
    certifications: ['CE', 'ATG'],
    price_per_unit: 32.0,
    price_unit: 'm2',
    price_updated_at: '2026-01-01',
    thermal_performance: 3.43,  # ~12cm coulisse standard
    lifespan_years: 30,
    grey_energy_kwh: 600,
    recyclable: false,
    biosourced: false,
    fire_class: 'E',
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.0,
    display_order: 13,
    active: true
  }
])

# ═══════════════════════════════════════════════════════════════════════════════
# CHÂSSIS (6)
# ═══════════════════════════════════════════════════════════════════════════════

Product.create!([
  {
    category: 'windows',
    subcategory: 'pvc',
    name: 'Châssis PVC double vitrage HR',
    brand: 'Rehau',
    description: 'Châssis PVC 70mm double vitrage haute résistance, entrée de gamme.',
    technical_specs: {
      'uw' => 1.4,
      'ug' => 1.0,
      'glazing' => 'double',
      'profile' => 'PVC 70mm',
      'air_class' => 3,
      'rain_class' => '7A',
      'wind_class' => 'C3'
    },
    certifications: ['CE'],
    price_per_unit: 450.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 1.4,   # Uw W/m²K (inversé = plus bas = mieux)
    lifespan_years: 40,
    grey_energy_kwh: nil,
    recyclable: true,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 3.9,
    display_order: 20,
    active: true
  },
  {
    category: 'windows',
    subcategory: 'pvc',
    name: 'Châssis PVC triple vitrage HR++',
    brand: 'Veka',
    description: 'PVC 82mm triple vitrage avec gaz argon, très faibles pertes thermiques.',
    technical_specs: {
      'uw' => 0.8,
      'ug' => 0.5,
      'glazing' => 'triple',
      'profile' => 'PVC 82mm',
      'gas_filling' => 'argon'
    },
    certifications: ['CE', 'Passive House'],
    price_per_unit: 750.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 0.8,
    lifespan_years: 40,
    grey_energy_kwh: nil,
    recyclable: true,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.5,
    display_order: 21,
    active: true
  },
  {
    category: 'windows',
    subcategory: 'alu',
    name: 'Châssis aluminium à rupture de pont thermique',
    brand: 'Schüco',
    description: 'Aluminium avec RPT, esthétique fine, résistance et durabilité maximales.',
    technical_specs: {
      'uw' => 1.3,
      'ug' => 1.0,
      'glazing' => 'double',
      'profile' => 'ALU RPT'
    },
    certifications: ['CE'],
    price_per_unit: 900.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 1.3,
    lifespan_years: 60,
    grey_energy_kwh: nil,
    recyclable: true,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.2,
    display_order: 22,
    active: true
  },
  {
    category: 'windows',
    subcategory: 'alu',
    name: 'Châssis aluminium triple vitrage premium',
    brand: 'Reynaers',
    description: 'Alu triple vitrage, performance passive, finition premium.',
    technical_specs: {
      'uw' => 0.9,
      'ug' => 0.5,
      'glazing' => 'triple',
      'profile' => 'ALU RPT+',
      'gas_filling' => 'krypton'
    },
    certifications: ['CE', 'Passive House'],
    price_per_unit: 1250.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 0.9,
    lifespan_years: 60,
    grey_energy_kwh: nil,
    recyclable: true,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.6,
    display_order: 23,
    active: true
  },
  {
    category: 'windows',
    subcategory: 'bois',
    name: 'Châssis bois double vitrage',
    brand: 'Internorm',
    description: 'Bois naturel double vitrage, esthétique traditionnelle, bonne isolation.',
    technical_specs: {
      'uw' => 1.1,
      'ug' => 0.7,
      'glazing' => 'double',
      'profile' => 'Bois massif',
      'wood_type' => 'pin nordique'
    },
    certifications: ['CE', 'FSC'],
    price_per_unit: 820.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 1.1,
    lifespan_years: 50,
    grey_energy_kwh: nil,
    recyclable: true,
    biosourced: true,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.3,
    display_order: 24,
    active: true
  },
  {
    category: 'windows',
    subcategory: 'bois',
    name: 'Châssis bois-alu triple vitrage',
    brand: 'Internorm HF 310',
    description: 'Intérieur bois + extérieur alu, triple vitrage, confort maximal.',
    technical_specs: {
      'uw' => 0.74,
      'ug' => 0.5,
      'glazing' => 'triple',
      'profile' => 'Bois-Alu',
      'gas_filling' => 'argon'
    },
    certifications: ['CE', 'Passive House', 'FSC'],
    price_per_unit: 1400.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 0.74,
    lifespan_years: 50,
    grey_energy_kwh: nil,
    recyclable: true,
    biosourced: true,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.7,
    display_order: 25,
    active: true
  }
])

# ═══════════════════════════════════════════════════════════════════════════════
# SYSTÈMES DE CHAUFFAGE (7)
# ═══════════════════════════════════════════════════════════════════════════════

Product.create!([
  {
    category: 'heating',
    name: 'Chaudière gaz condensation',
    brand: 'Vaillant ecoTEC',
    description: 'Gaz condensation haute efficacité, remplacement standard le plus courant.',
    technical_specs: {
      'cop' => 1.07,
      'efficiency_pct' => 109,
      'energy_source' => 'gaz_naturel',
      'power_kw' => 24,
      'type' => 'condensation'
    },
    certifications: ['CE', 'ErP A'],
    price_per_unit: 3200.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 1.09,
    lifespan_years: 20,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: false,
    flanders_grant_eligible: false,
    brussels_grant_eligible: false,
    vat_6_eligible: true,
    average_rating: 4.0,
    display_order: 30,
    active: true
  },
  {
    category: 'heating',
    name: 'Pompe à chaleur air-eau Mitsubishi Ecodan',
    brand: 'Mitsubishi',
    description: 'PAC air-eau, COP 3.8, compatible radiateurs basse température.',
    technical_specs: {
      'cop' => 3.8,
      'scop' => 4.5,
      'energy_source' => 'electricite',
      'power_kw' => 8.5,
      'type' => 'air_eau',
      'min_temp_outdoor' => -25
    },
    certifications: ['CE', 'ErP A+++'],
    price_per_unit: 12000.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 3.8,
    lifespan_years: 20,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.5,
    display_order: 31,
    active: true
  },
  {
    category: 'heating',
    name: 'Pompe à chaleur air-eau Daikin Altherma 3',
    brand: 'Daikin',
    description: 'PAC air-eau inverter, référence marché belge, très fiable.',
    technical_specs: {
      'cop' => 4.2,
      'scop' => 5.1,
      'energy_source' => 'electricite',
      'power_kw' => 11,
      'type' => 'air_eau',
      'smart_grid' => true
    },
    certifications: ['CE', 'ErP A+++'],
    price_per_unit: 14500.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 4.2,
    lifespan_years: 20,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.6,
    display_order: 32,
    active: true
  },
  {
    category: 'heating',
    name: 'Pompe à chaleur géothermique Viessmann',
    brand: 'Viessmann',
    description: 'PAC sol-eau, performance maximale, COP 5+, investissement premium.',
    technical_specs: {
      'cop' => 5.2,
      'energy_source' => 'geothermie',
      'power_kw' => 10,
      'type' => 'geothermique',
      'probe_depth_m' => 100
    },
    certifications: ['CE', 'ErP A+++'],
    price_per_unit: 22000.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 5.2,
    lifespan_years: 25,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.4,
    display_order: 33,
    active: true
  },
  {
    category: 'heating',
    name: 'Chaudière biomasse granulés Ökofen',
    brand: 'Ökofen',
    description: 'Chaudière pellets automatique, CO2 neutre, idéale hors réseau gaz.',
    technical_specs: {
      'cop' => 1.0,
      'efficiency_pct' => 95,
      'energy_source' => 'biomasse_pellets',
      'power_kw' => 25,
      'type' => 'biomasse'
    },
    certifications: ['CE', 'ErP A+'],
    price_per_unit: 18000.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 0.95,
    lifespan_years: 25,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: true,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.1,
    display_order: 34,
    active: true
  },
  {
    category: 'heating',
    name: 'Chaudière mazout condensation',
    brand: 'De Dietrich',
    description: 'Mazout condensation haute efficacité, alternative en zone hors gaz.',
    technical_specs: {
      'cop' => 1.0,
      'efficiency_pct' => 105,
      'energy_source' => 'mazout',
      'power_kw' => 24,
      'type' => 'condensation'
    },
    certifications: ['CE', 'ErP A'],
    price_per_unit: 4200.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 1.05,
    lifespan_years: 20,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: false,
    flanders_grant_eligible: false,
    brussels_grant_eligible: false,
    vat_6_eligible: true,
    average_rating: 3.8,
    display_order: 35,
    active: true
  },
  {
    category: 'heating',
    name: 'Système solaire combiné chaudière + panneaux',
    brand: 'Buderus',
    description: 'Chaudière gaz + capteurs solaires thermiques, 40-60% couverture ECS.',
    technical_specs: {
      'cop' => 1.4,
      'energy_source' => 'gaz_solaire',
      'solar_coverage_pct' => 50,
      'type' => 'solaire_combine'
    },
    certifications: ['CE', 'Solar Keymark'],
    price_per_unit: 8500.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 1.4,
    lifespan_years: 20,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: false,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.0,
    display_order: 36,
    active: true
  }
])

# ═══════════════════════════════════════════════════════════════════════════════
# PANNEAUX SOLAIRES (3)
# ═══════════════════════════════════════════════════════════════════════════════

Product.create!([
  {
    category: 'solar',
    name: 'Panneau solaire monocristallin SunPower',
    brand: 'SunPower',
    description: 'Rendement maximum (22%), idéal petites surfaces.',
    technical_specs: {
      'efficiency_pct' => 22,
      'power_wp' => 420,
      'type' => 'monocristallin',
      'degradation_annual_pct' => 0.3
    },
    certifications: ['CE', 'IEC 61215'],
    price_per_unit: 1.80,
    price_unit: 'kWc',
    price_updated_at: '2026-01-01',
    thermal_performance: 22.0,
    lifespan_years: 30,
    grey_energy_kwh: nil,
    recyclable: true,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.7,
    display_order: 40,
    active: true
  },
  {
    category: 'solar',
    name: 'Panneau solaire polycristallin Jinko',
    brand: 'Jinko Solar',
    description: 'Meilleur rapport qualité/prix, rendement 17%, très répandu en Belgique.',
    technical_specs: {
      'efficiency_pct' => 17,
      'power_wp' => 340,
      'type' => 'polycristallin',
      'degradation_annual_pct' => 0.5
    },
    certifications: ['CE', 'IEC 61215'],
    price_per_unit: 1.20,
    price_unit: 'kWc',
    price_updated_at: '2026-01-01',
    thermal_performance: 17.0,
    lifespan_years: 25,
    grey_energy_kwh: nil,
    recyclable: true,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.2,
    display_order: 41,
    active: true
  },
  {
    category: 'solar',
    name: 'Tuiles solaires Tesla Solar Roof',
    brand: 'Tesla',
    description: 'Tuiles intégrées esthétiques, idéales rénovation toiture complète.',
    technical_specs: {
      'efficiency_pct' => 14,
      'type' => 'tuiles_integrees',
      'aesthetic' => 'premium',
      'waterproof' => true
    },
    certifications: ['CE', 'UL'],
    price_per_unit: 4.50,
    price_unit: 'kWc',
    price_updated_at: '2026-01-01',
    thermal_performance: 14.0,
    lifespan_years: 30,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: false,
    brussels_grant_eligible: false,
    vat_6_eligible: true,
    average_rating: 4.3,
    display_order: 42,
    active: true
  }
])

# ═══════════════════════════════════════════════════════════════════════════════
# CHAUFFE-EAU (3)
# ═══════════════════════════════════════════════════════════════════════════════

Product.create!([
  {
    category: 'hot_water',
    name: 'Chauffe-eau thermodynamique Atlantic Calypso',
    brand: 'Atlantic',
    description: 'PAC air-eau pour ECS, COP 3.5, économie 70% vs électrique classique.',
    technical_specs: {
      'cop' => 3.5,
      'capacity_l' => 200,
      'type' => 'thermodynamique',
      'energy_source' => 'electricite'
    },
    certifications: ['CE', 'ErP A+'],
    price_per_unit: 1200.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 3.5,
    lifespan_years: 15,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.4,
    display_order: 50,
    active: true
  },
  {
    category: 'hot_water',
    name: 'Chauffe-eau solaire thermique Viessmann',
    brand: 'Viessmann',
    description: 'Capteurs solaires + ballon, 60% couverture ECS solaire.',
    technical_specs: {
      'cop' => 4.0,
      'capacity_l' => 300,
      'type' => 'solaire_thermique',
      'solar_coverage_pct' => 60
    },
    certifications: ['CE', 'Solar Keymark'],
    price_per_unit: 3800.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 4.0,
    lifespan_years: 20,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: true,
    flanders_grant_eligible: true,
    brussels_grant_eligible: true,
    vat_6_eligible: true,
    average_rating: 4.2,
    display_order: 51,
    active: true
  },
  {
    category: 'hot_water',
    name: 'Chauffe-eau électrique classique 200L',
    brand: 'Ariston',
    description: 'Résistance électrique classique, installation simple, prix bas.',
    technical_specs: {
      'cop' => 1.0,
      'capacity_l' => 200,
      'type' => 'electrique_classique',
      'energy_source' => 'electricite'
    },
    certifications: ['CE'],
    price_per_unit: 380.0,
    price_unit: 'unit',
    price_updated_at: '2026-01-01',
    thermal_performance: 1.0,
    lifespan_years: 12,
    grey_energy_kwh: nil,
    recyclable: false,
    biosourced: false,
    fire_class: nil,
    wallonie_grant_eligible: false,
    flanders_grant_eligible: false,
    brussels_grant_eligible: false,
    vat_6_eligible: true,
    average_rating: 3.5,
    display_order: 52,
    active: true
  }
])

puts "  ✅ #{Product.count} produits créés (isolants, châssis, chauffage, solaire, chauffe-eau)"
