default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: ren0vate_development

test:
  <<: *default
  database: ren0vate_test

production:
  primary:
    <<: *default
    database: ren0vate_production
  queue:
    <<: *default
    database: ren0vate_production
  cable:
    <<: *default
    database: ren0vate_production_cable
  cache:
    <<: *default
    database: ren0vate_production
